<?xml version="1.0" encoding="UTF-8" ?>
<!--两种本地引入方法-->
<!--<!DOCTYPE students SYSTEM "student.dtd">-->
<!DOCTYPE students [
		<!ELEMENT students (student*) >
		<!ELEMENT student (name,age,sex)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT sex (#PCDATA)>
		<!ATTLIST student number ID #REQUIRED>
		] >
<students>
    <student number="s1">
        <name>zhangsan</name>
        <age>17</age>
        <sex>male</sex>
    </student>
</students>